# This file is used to generate config.anal, which would be used to
# run the GFS analysis.  The scripts and code for the analysis are not
# provided in this release, so this config file is ignored.

config_anal:
  filename: config.anal
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.anal ##########
    # Analysis specific
    
    echo "BEGIN: config.anal"
    
    if [ $DONST = "YES" ]; then
        . $EXPDIR/config.nsst
    fi
   
    export npe_anal={doc.partition_common.resources.run_anal[0].mpi_ranks}
    export npe_node_anal={doc.partition_common.resources.run_anal[0].max_ppn}
    export nth_anal={doc.partition_common.resources.run_anal[0].OMP_NUM_THREADS}
    export nth_cycle=24
    if [[ "$machine" = "WCOSS_DELL_P3" ]]; then
        export nth_anal=14
        export nth_cycle=28
    fi
    if [[ "$machine" == "WCOSS_C" ]]; then
        export memory_anal="3072M"
    elif [[ "$machine" == "GAEA" ]]; then
        export memory_anal="3072M"
    fi
 
    if [[ "$CDUMP" = "gfs" ]] ; then
        export USE_RADSTAT="NO" # This can be only used when bias correction is not-zero.
        export GENDIAG="NO"
        export SETUP='diag_rad=.false.,diag_pcp=.false.,diag_conv=.false.,diag_ozone=.false.,write_diag(3)=.false.,'
        export DIAG_TARBALL="NO"
    fi
    
    export ANALYSISSH="$HOMEgsi/scripts/exglobal_analysis_fv3gfs.sh.ecf"
    export npe_gsi=$npe_anal
    export LEVS_ENKF=$((LEVS-1))

    export GSNDBF=/dev/null
    export AMSREBF=/dev/null
    export SSMITBF=/dev/null
    export AMSR2BF=/dev/null

    # Set directory and structure for COMIN_OBS
    export COMIN_OBS="$DMPDIR/$CDUMP$DUMP_SUFFIX.$PDY/$cyc"

    # export REALTIME="{tools.YES_NO(doc.settings.realtime)}"   # Run GFS AWIPS
    
    # Set CONVINFO and SATINFO for retrospective parallels
    if [ $REALTIME = "NO" ]; then

      # Set CONVINFO
      if [[ "$CDATE" -ge "2018022818" ]]; then
        export CONVINFO=$FIXgsi/fv3_historical/global_convinfo.txt.2018022818
      elif [[ "$CDATE" -ge "2018010512" ]]; then
        export CONVINFO=$FIXgsi/fv3_historical/global_convinfo.txt.2018010512
      elif [[ "$CDATE" -ge "2017071912" ]]; then
        export CONVINFO=$FIXgsi/fv3_historical/global_convinfo.txt.2017071912
      elif [[ "$CDATE" -ge "2016031512" ]]; then
        export CONVINFO=$FIXgsi/fv3_historical/global_convinfo.txt.2016031512
      elif [[ "$CDATE" -ge "2014041400" ]]; then
        export CONVINFO=$FIXgsi/fv3_historical/global_convinfo.txt.2014041400
      else
        echo "WARNING: No CONVINFO for $CDATE"
      fi

      # Set OZINFO
      if [[ "$CDATE" -ge "2018110700" ]]; then
          export OZINFO=$FIXgsi/fv3_historical/global_ozinfo.txt.2018110700
      elif [[ "$CDATE" -ge "2015110500" ]]; then
          export OZINFO=$FIXgsi/fv3_historical/global_ozinfo.txt.2015110500
      else
          echo "WARNING: No OZINFO for $CDATE"
      fi

      # Set SATINFO
      if [[ "$CDATE" -ge "2018053012" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2018053012
      elif [[ "$CDATE" -ge "2018021212" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2018021212
      elif [[ "$CDATE" -ge "2017103118" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2017103118
      elif [[ "$CDATE" -ge "2017031612" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2017031612
      elif [[ "$CDATE" -ge "2017030812" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2017030812
      elif [[ "$CDATE" -ge "2016110812" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2016110812
      elif [[ "$CDATE" -ge "2016090912" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2016090912
      elif [[ "$CDATE" -ge "2016020312" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2016020312
      elif [[ "$CDATE" -ge "2016011912" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2016011912
      elif [[ "$CDATE" -ge "2015111012" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2015111012
      elif [[ "$CDATE" -ge "2015100118" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2015100118
      elif [[ "$CDATE" -ge "2015070218" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2015070218
      elif [[ "$CDATE" -ge "2015011412" ]]; then
        export SATINFO=$FIXgsi/fv3_historical/global_satinfo.txt.2015011412
      else
        echo "WARNING: No SATINFO for $CDATE"
      fi
    fi

    echo "END: config.anal"
