#!/bin/ksh
#
# set up base variables
# execute with dot
#
echo
echo `date` $0 $* setbase begin
echo

echo
echo `date` $0 set environment and experiment id
echo

NDATE=${NDATE:-/gpfs/dell1/nco/ops/nwprod/prod_util.v1.1.1/exec/ips/ndate}
#DHOU, 01/03/2013 add this block to generate the machine name related variables
  machl=`uname -n | cut -c1`

if [[ $machl = v ]] || [[ $machl = m ]]; then
  PTMP=/gpfs/dell3/ptmp
  STMP=/gpfs/dell3/stmp

  envir=$(basename $(dirname $(dirname $(pwd) ) ) | cut -c3-)
  echo envir=$envir

  expid=$(basename $(dirname $(dirname $(dirname $(pwd) ) ) ) )
  id=`echo $expid|cut -c3-4`
  echo expid=$expid
  echo id=$id
fi

#echo $LOGNAME
#exit

echo
echo `date` $0 set directory tree locations
echo

  echo directory locations for running in $LOGNAME account
  echo

  export basesource=/global/save/$LOGNAME/s/$expid
  export baseoutput=/ptmp/$LOGNAME/o/$expid
  export basetmp=/ptmp/$LOGNAME/o/$expid
  export baseptmp=/ptmp/$LOGNAME/o/$expid

  export basebin=$basesource/nw$envir/control

  export baselog=/ptmp/$LOGNAME/o/$expid
  export basedgfs=/global/noscrub/$LOGNAME/o
  export basedgens=/ptmp/$LOGNAME/o
  export baseinitarch=/global/mirror/$LOGNAME/o/$expid

#For DELL
if [[ $machl = v ]] || [[ $machl = m ]]; then
  export PTMP=/gpfs/dell3/ptmp
  export STMP=/gpfs/dell3/stmp
  group=emc/modeling
  group=emc/retros
  group=`pwd|cut -d'/' -f2`
  export basesource=/gpfs/dell2/$group/noscrub/$LOGNAME/WCOSS/$expid
  export baseoutput=$PTMP/$LOGNAME/o/$expid
  export basetmp=$STMP/$LOGNAME/o/$expid
  export baseptmp=$PTMP/$LOGNAME/o/$expid
  export baselog=$PTMP/$LOGNAME/o/$expid
  export basedgfs=
 #exit
fi
#For DELL end

  export account=GEN-T2O
  export group=g01
  export group=devonprod
  export classs=1
  export classp=devhigh
  export classp=dev

if [[ $machl = v ]] || [[ $machl = m ]]; then
# For DELL
  export account=GEN-T2O
  #export group=emc/modeling
  # RLW 20140903 modify selected settings for emc.enspara on WCOSS
  if [[ "$LOGNAME" = "emc.enspara" ]]; then
    export group=emc/verification
    userin="emc.enspara/Xianwu.Xue"
    userout="emc.enspara"
    usergfs="Xianwu.Xue"
    zq_setbase_hh=`date +%H`
    echo zq_setbase_hh=$zq_setbase_hh
    zq_setbase_runhigh=no      # default
    zq_setbase_runhigh=yes
    if (( zq_setbase_hh > 23 )) || (( zq_setbase_hh < 10 )) ; then
      zq_setbase_runhigh=no
      zq_setbase_runhigh=yes   # default
      zq_setbase_testc=`date +%Y%m%d`
      zq_setbase_testc=`$NDATE -24`
      echo zq_setbase_testc=$zq_setbase_testc
      zq_setbase_testj=`echo ${LSB_JOBNAME}333333333333 | cut -c3-12`
      echo zq_setbase_testj=$zq_setbase_testj
      if [[ "$zq_setbase_testj" > "$zq_setbase_testc" ]]; then
        zq_setbase_runhigh=no  # default
        zq_setbase_runhigh=yes
      fi
    fi
    echo zq_setbase_runhigh=$zq_setbase_runhigh
    if [[ "$zq_setbase_runhigh" =  "yes" ]]; then
      export classs=devhigh_shared
      export classp=devhigh
    else
      export classs=dev_shared
      export classp=dev
    fi
  else
    export group=emc/retros
    userin=$LOGNAME
    userout=$LOGNAME
    usergfs=$LOGNAME
    export classs=dev_shared
    export classp=dev
  fi
  # RLW 20141008 modify to obtain and use version for vertical structure
  . /gpfs/dell2/$group/noscrub/$userin/s/$expid/nw$envir/gefs_legacy.v*/versions/gefs_legacy.ver
  echo gefs_legacy_ver=${gefs_legacy_ver}
  export basesource=/gpfs/dell2/$group/noscrub/$userin/s/$expid
  export basebin=$basesource/nw$envir/gefs_legacy.${gefs_legacy_ver}/control
  export baseoutput=$PTMP/$userout/o/$expid
  export basetmp=$STMP/$userout/o/$expid
  export basetmp=$PTMP/$userout/o/$expid
  export baseptmp=$PTMP/$userout/o/$expid
  export basedgfs=/$group/noscrub/$usergfs/o
# RLW 20141010 use NCO parallel/prod for gfs testing
  export basedgfs=     # important to keep this line unchanged.----- Dingchen 20210202
  #export basedgfs=/gpfs/td1/emc/ensemble/noscrub/$usergfs/o
  export basewait=$baseoutput/wait
# For DELL end
fi  

echo
echo basesource=$basesource
echo baseoutput=$baseoutput
echo
echo basetmp=$basetmp
echo baseptmp=$baseptmp
echo basebin=$basebin
echo
echo basedgfs=$basedgfs
echo basedgens=$basedgens
echo
echo account=$account
echo group=$group
echo
echo classs=$classs
echo classp=$classp
echo
echo `date` $0 $* setbase end
echo
